export const constants = {
  width: 800,
  height: 600,
  playerSpeed: 300,
  playerDrag: 600,
  projectileSpeed: 500,
  maxProjectiles: 50,
  playerColor: 0x859900,
  enemyColor: 0xff0000,
  projectileColor: 0xffffff,
  starColor: 0x606060,
  starTileSize: 64,
  starCount: 100,
  starScrollSpeed: 0.5,
  maxEnemies: 50,
  scorePerTier: 100,
  // difficulty progression: every N points or ~60s elapsed
  difficultyTimeStepMs: 60000,
  maxDifficultyTier: 6,
  baseInterval: 2000,
  intervalDecrement: 300,
  minInterval: 500,
  enemySpawnMinX: 50,
  enemySpawnMaxX: 750,
  enemyBaseSpeed: 100,
  enemySpeedIncrement: 50,
  enemyTrackStrengthBase: 0.75,
  enemyTrackStrengthIncrement: 0.05,
  enemySwayAmplitudeBase: 40,
  enemySwayAmplitudeIncrement: 8,
  enemySwayFrequencyBase: 0.002,
  enemySwayFrequencyIncrement: 0.0004,
  enemyDiveChanceBase: 0.1, // per second
  enemyDiveChanceIncrement: 0.05,
  enemyDiveSpeedMultiplier: 1.6,
  enemyDiveDurationMin: 400,
  enemyDiveDurationMax: 900,
  pointsPerHit: 10,
  // how often an enemy will start an evasion (in ms)
  evasionIntervalMin: 800,
  evasionIntervalMax: 2500,
  // how long each evasion lasts (in ms)
  evasionDurationMin: 300,
  evasionDurationMax: 800,
  // how fast they dodge laterally (pixels/sec)
  evasionSpeed: 200,
  bottomMargin: 100,
};
